I want to see if models can do credit assignment all by themselves through replay.

In [1]:
import mlx.core as mx
from mlx_lm import load
import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

model, tokenizer = load("mlx-community/Qwen2.5-Coder-7B-Instruct-4bit")

def ocsd(messages):
    ids = mx.array(tokenizer.apply_chat_template(messages))
    hidden = model.model(mx.concat([ids, ids])[None])[0,len(ids):]
    logits = model.lm_head(hidden)
    probs = mx.softmax(logits, axis=-1)
    labels = ids[1:]
    pred_ids = mx.argsort(probs, axis=-1)[:,:-(3+1):-1]
    mx.eval(pred_ids)

    rows = []
    for i in range(len(labels)):
        def cell(id):
            token = tokenizer.decode([id.tolist()], skip_special_tokens=False)
            return f"{token!r} @ {probs[i,id]:.3f}"
        
        row = {"label": cell(labels[i])}
        for j, pred_id in enumerate(pred_ids[i]):
            row[f"pred_{j}"] = cell(pred_id)
        rows.append(row)
    df = pd.DataFrame(rows)
    return df

ocsd([
    {
        "role": "user",
        "content": "Pick two numbers."
    },
    {
        "role": "assistant",
        "content": "2 and 3."
    },
    {
        "role": "user",
        "content": "Pick again! The first number must be odd and the second number must be even."
    }
])

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

,label,pred_0,pred_1,pred_2
0,'system' @ 0.000,'<|im_start|>' @ 0.857,'<|im_end|>' @ 0.112,'1' @ 0.020
1,'\n' @ 0.976,'\n' @ 0.976,'<|im_end|>' @ 0.008,'<|im_start|>' @ 0.006
2,'You' @ 0.000,'1' @ 0.384,'5' @ 0.255,'7' @ 0.146
3,' are' @ 0.007,' picked' @ 0.318,' can' @ 0.112,' got' @ 0.100
4,' Q' @ 0.022,' correct' @ 0.204,' a' @ 0.144,' welcome' @ 0.097
5,'wen' @ 1.000,'wen' @ 1.000,' Wen' @ 0.000,'W' @ 0.000
6,"',' @ 0.971","',' @ 0.971",'<|im_end|>' @ 0.010,'.' @ 0.008
7,' created' @ 0.617,' created' @ 0.617,' an' @ 0.190,' a' @ 0.072
8,' by' @ 1.000,' by' @ 1.000,'<|im_end|>' @ 0.000,' and' @ 0.000
9,' Alibaba' @ 1.000,' Alibaba' @ 1.000,' Ali' @ 0.000,'阿里' @ 0.000
10,' Cloud' @ 1.000,' Cloud' @ 1.000,'Cloud' @ 0.000,' cloud' @ 0.000
11,'.' @ 0.974,'.' @ 0.974,"',' @ 0.017",' and' @ 0.004
12,' You' @ 0.223,' I' @ 0.515,' You' @ 0.223,'<|im_end|>' @ 0.099
13,' are' @ 0.994,' are' @ 0.994,' can' @ 0.004,"""'re"" @ 0.001"
14,' a' @ 0.990,' a' @ 0.990,' an' @ 0.005,' here' @ 0.002
15,' helpful' @ 0.989,' helpful' @ 0.989,' language' @ 0.003,' large' @ 0.001
16,' assistant' @ 0.995,' assistant' @ 0.995,' AI' @ 0.002,' Assistant' @ 0.001
17,'.' @ 0.884,'.' @ 0.884,'.\n' @ 0.085,'.\n\n' @ 0.011
18,'<|im_end|>' @ 0.817,'<|im_end|>' @ 0.817,' I' @ 0.042,' How' @ 0.031
19,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'\n\n' @ 0.000
20,'<|im_start|>' @ 0.003,'<|endoftext|>' @ 0.997,'<|im_start|>' @ 0.003,'<|im_end|>' @ 0.000
21,'user' @ 0.000,'\n' @ 0.956,'<|endoftext|>' @ 0.019,'<|im_start|>' @ 0.014
22,'\n' @ 0.998,'\n' @ 0.998,'<|im_start|>' @ 0.001,'<|im_end|>' @ 0.001
23,'Pick' @ 0.270,'Sure' @ 0.301,'Pick' @ 0.270,'I' @ 0.166
24,' two' @ 0.581,' two' @ 0.581,' again' @ 0.347,' a' @ 0.020
25,' numbers' @ 0.996,' numbers' @ 0.996,' new' @ 0.002,' more' @ 0.001
26,'.' @ 0.481,'.' @ 0.481,' again' @ 0.159,' where' @ 0.077
27,'<|im_end|>' @ 0.087,' The' @ 0.883,'<|im_end|>' @ 0.087,' One' @ 0.022
28,'\n' @ 1.000,'\n' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
29,'<|im_start|>' @ 1.000,'<|im_start|>' @ 1.000,'<|endoftext|>' @ 0.000,'<|im_end|>' @ 0.000
30,'assistant' @ 0.000,'<|im_start|>' @ 0.937,'\n' @ 0.033,'<|im_end|>' @ 0.028
31,'\n' @ 0.002,"',' @ 0.308",'Sure' @ 0.287,'Alright' @ 0.085
32,'2' @ 0.039,'1' @ 0.271,'5' @ 0.239,'7' @ 0.214
33,' and' @ 0.924,' and' @ 0.924,'7' @ 0.021,'1' @ 0.020
34,' ' @ 1.000,' ' @ 1.000,' odd' @ 0.000,' -' @ 0.000
35,'3' @ 0.760,'3' @ 0.760,'5' @ 0.170,'7' @ 0.045
36,'.' @ 0.925,'.' @ 0.925,'<|im_end|>' @ 0.064,"',' @ 0.005"
37,'<|im_end|>' @ 0.996,'<|im_end|>' @ 0.996,' The' @ 0.001,' Is' @ 0.000
38,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'\r\n' @ 0.000
39,'<|im_start|>' @ 0.000,'<|endoftext|>' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
40,'user' @ 0.000,'\n' @ 0.814,'<|endoftext|>' @ 0.148,'<|im_end|>' @ 0.024
41,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'<|im_start|>' @ 0.000
42,'Pick' @ 0.644,'Pick' @ 0.644,'I' @ 0.151,'Sorry' @ 0.026
43,' again' @ 0.712,' again' @ 0.712,' two' @ 0.201,' numbers' @ 0.022
44,'!' @ 0.992,'!' @ 0.992,"',' @ 0.005",'.' @ 0.002
45,' The' @ 0.967,' The' @ 0.967,' This' @ 0.026,'<|im_end|>' @ 0.004
46,' first' @ 1.000,' first' @ 1.000,' numbers' @ 0.000,' second' @ 0.000
47,' number' @ 1.000,' number' @ 1.000,' must' @ 0.000,' odd' @ 0.000
48,' must' @ 1.000,' must' @ 1.000,' should' @ 0.000,' has' @ 0.000
49,' be' @ 1.000,' be' @ 1.000,' быть' @ 0.000,'<|im_end|>' @ 0.000
50,' odd' @ 0.999,' odd' @ 0.999,' even' @ 0.001,' an' @ 0.000
51,' and' @ 0.999,' and' @ 0.999,"',' @ 0.001",'.' @ 0.000
52,' the' @ 1.000,' the' @ 1.000,'<|im_end|>' @ 0.000,' second' @ 0.000
53,' second' @ 1.000,' second' @ 1.000,'第二' @ 0.000,'second' @ 0.000
54,' number' @ 1.000,' number' @ 1.000,' must' @ 0.000,' one' @ 0.000
55,' must' @ 1.000,' must' @ 1.000,'必须' @ 0.000,' should' @ 0.000
56,' be' @ 1.000,' be' @ 1.000,' быть' @ 0.000,'<|im_end|>' @ 0.000
57,' even' @ 1.000,' even' @ 1.000,' an' @ 0.000,' positive' @ 0.000
58,'.' @ 1.000,'.' @ 1.000,'<|im_end|>' @ 0.000,'.\n' @ 0.000
59,'<|im_end|>' @ 1.000,'<|im_end|>' @ 1.000,'<|im_start|>' @ 0.000,' Can' @ 0.000
60,'\n' @ 1.000,'\n' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000

There's credit attribution, but it falls off after the first instance because the model's disagreement isn't reflected in the trajectory and so it tries to conform with what's already there, even if it's incorrect. I think this means we can't do a naive offline approach. Maybe we can try chunks?

Let's try a successful trajectory with some unnecessary steps.

In [2]:
ocsd([
    {
        "role": "user",
        "content": "What is the capital of Foo?"
    },
    {
        "role": "assistant",
        "content": "Ethan is cool."
    },
    {
        "role": "user",
        "content": "Huh."
    },
    {
        "role": "assistant",
        "content": "I love tacos."
    },
    {
        "role": "user",
        "content": "Okay."
    },
    {
        "role": "assistant",
        "content": "The capital of Foo is Bar."
    },
    {
        "role": "user",
        "content": "Correct!"
    }
])

,label,pred_0,pred_1,pred_2
0,'system' @ 0.000,'<|im_start|>' @ 0.504,'<|im_end|>' @ 0.438,':\n' @ 0.022
1,'\n' @ 0.974,'\n' @ 0.974,'<|im_end|>' @ 0.012,'<|im_start|>' @ 0.005
2,'You' @ 0.016,'Thank' @ 0.467,'I' @ 0.326,'Yes' @ 0.048
3,' are' @ 0.192,"""'re"" @ 0.680",' are' @ 0.192,' got' @ 0.085
4,' Q' @ 0.007,' correct' @ 0.810,' right' @ 0.060,' welcome' @ 0.043
5,'wen' @ 1.000,'wen' @ 1.000,' Wen' @ 0.000,'W' @ 0.000
6,"',' @ 0.996","',' @ 0.996",'<|im_end|>' @ 0.002,'.' @ 0.001
7,' created' @ 0.378,' created' @ 0.378,' an' @ 0.309,' a' @ 0.272
8,' by' @ 1.000,' by' @ 1.000,'<|im_end|>' @ 0.000,' and' @ 0.000
9,' Alibaba' @ 1.000,' Alibaba' @ 1.000,' Ali' @ 0.000,'阿里' @ 0.000
10,' Cloud' @ 1.000,' Cloud' @ 1.000,'Cloud' @ 0.000,' cloud' @ 0.000
11,'.' @ 0.995,'.' @ 0.995,"',' @ 0.004",' and' @ 0.001
12,' You' @ 0.539,' You' @ 0.539,' I' @ 0.337,'<|im_end|>' @ 0.066
13,' are' @ 0.998,' are' @ 0.998,' can' @ 0.001,' have' @ 0.000
14,' a' @ 0.982,' a' @ 0.982,' an' @ 0.007,' here' @ 0.006
15,' helpful' @ 0.980,' helpful' @ 0.980,' language' @ 0.005,' large' @ 0.005
16,' assistant' @ 0.996,' assistant' @ 0.996,' and' @ 0.001,' AI' @ 0.001
17,'.' @ 0.978,'.' @ 0.978,' designed' @ 0.008,' with' @ 0.004
18,'<|im_end|>' @ 0.892,'<|im_end|>' @ 0.892,' How' @ 0.033,' Is' @ 0.024
19,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,"""'\n"" @ 0.000"
20,'<|im_start|>' @ 0.000,'<|endoftext|>' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
21,'user' @ 0.000,'\n' @ 0.941,'<|endoftext|>' @ 0.048,'<|im_start|>' @ 0.007
22,'\n' @ 0.999,'\n' @ 0.999,'<|im_end|>' @ 0.001,'<|im_start|>' @ 0.000
23,'What' @ 0.293,'What' @ 0.293,'I' @ 0.154,'Thank' @ 0.111
24,' is' @ 0.861,' is' @ 0.861,"""'s"" @ 0.043",' can' @ 0.029
25,' the' @ 0.814,' the' @ 0.814,' your' @ 0.148,' ' @ 0.014
26,' capital' @ 0.922,' capital' @ 0.922,' weather' @ 0.013,' population' @ 0.008
27,' of' @ 0.998,' of' @ 0.998,' city' @ 0.002,' and' @ 0.000
28,' Foo' @ 0.517,' Foo' @ 0.517,' Peru' @ 0.096,' China' @ 0.081
29,'?' @ 0.887,'?' @ 0.887,'?\n' @ 0.079,'?\n\n' @ 0.022
30,'<|im_end|>' @ 0.995,'<|im_end|>' @ 0.995,' I' @ 0.001,' Answer' @ 0.001
31,'\n' @ 1.000,'\n' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
32,'<|im_start|>' @ 1.000,'<|im_start|>' @ 1.000,'' @ 0.000,'' @ 0.000
33,'assistant' @ 0.000,'<|im_start|>' @ 0.672,'<|im_end|>' @ 0.196,'\n' @ 0.124
34,'\n' @ 0.135,' The' @ 0.700,'\n' @ 0.135,'The' @ 0.052
35,'E' @ 0.006,'The' @ 0.738,'Bar' @ 0.208,'I' @ 0.026
36,'than' @ 0.994,'than' @ 0.994,'ston' @ 0.001,'van' @ 0.000
37,' is' @ 0.981,' is' @ 0.981,'<|im_end|>' @ 0.006,'.' @ 0.006
38,' cool' @ 0.938,' cool' @ 0.938,' correct' @ 0.013,' not' @ 0.008
39,'.' @ 0.973,'.' @ 0.973,"',' @ 0.013",'<|im_end|>' @ 0.006
40,'<|im_end|>' @ 0.996,'<|im_end|>' @ 0.996,' The' @ 0.001,' How' @ 0.001
41,'\n' @ 1.000,'\n' @ 1.000,'\r\n' @ 0.000,'<|im_end|>' @ 0.000
42,'<|im_start|>' @ 0.000,'<|endoftext|>' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
43,'user' @ 0.000,'<|endoftext|>' @ 0.738,'\n' @ 0.229,'<|im_start|>' @ 0.024
44,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'<|im_start|>' @ 0.000
45,'H' @ 0.588,'H' @ 0.588,'I' @ 0.133,'No' @ 0.050
46,'uh' @ 1.000,'uh' @ 1.000,' uh' @ 0.000,' huh' @ 0.000
47,'.' @ 0.932,'.' @ 0.932,'?' @ 0.063,"',' @ 0.002"
48,'<|im_end|>' @ 0.996,'<|im_end|>' @ 0.996,' How' @ 0.001,' Can' @ 0.001
49,'\n' @ 1.000,'\n' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
50,'<|im_start|>' @ 1.000,'<|im_start|>' @ 1.000,'' @ 0.000,'' @ 0.000
51,'assistant' @ 0.000,'<|im_start|>' @ 1.000,'<|im_end|>' @ 0.000,'assistant' @ 0.000
52,'\n' @ 0.868,'\n' @ 0.868,'<|im_end|>' @ 0.114,'.' @ 0.013
53,'I' @ 0.978,'I' @ 0.978,'The' @ 0.014,'Sorry' @ 0.002
54,' love' @ 0.995,' love' @ 0.995,' like' @ 0.002,' enjoy' @ 0.001
55,' tacos' @ 0.999,' tacos' @ 0.999,' pizza' @ 0.000,' programming' @ 0.000
56,'.' @ 0.999,'.' @ 0.999,'!' @ 0.001,'<|im_end|>' @ 0.000
57,'<|im_end|>' @ 1.000,'<|im_end|>' @ 1.000,' How' @ 0.000,' Did' @ 0.000
58,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'\r\n' @ 0.000
59,'<|im_start|>' @ 0.000,'<|endoftext|>' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
60,'user' @ 0.054,'\n' @ 0.812,'<|endoftext|>' @ 0.071,'user' @ 0.054
61,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'<|im_start|>' @ 0.000
62,'Okay' @ 0.986,'Okay' @ 0.986,'What' @ 0.002,'I' @ 0.002
63,'.' @ 0.996,'.' @ 0.996,"',' @ 0.004",'<|im_end|>' @ 0.000
64,'<|im_end|>' @ 0.999,'<|im_end|>' @ 0.999,' What' @ 0.000,'<|im_start|>' @ 0.000
65,'\n' @ 1.000,'\n' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
66,'<|im_start|>' @ 1.000,'<|im_start|>' @ 1.000,'<|endoftext|>' @ 0.000,'' @ 0.000
67,'assistant' @ 0.000,'<|im_start|>' @ 1.000,'<|im_end|>' @ 0.000,'assistant' @ 0.000
68,'\n' @ 0.994,'\n' @ 0.994,'<|im_end|>' @ 0.006,'\n\n' @ 0.000
69,'The' @ 0.984,'The' @ 0.984,'Sorry' @ 0.003,'I' @ 0.003
70,' capital' @ 0.999,' capital' @ 0.999,' correct' @ 0.001,' answer' @ 0.000
71,' of' @ 1.000,' of' @ 1.000,' is' @ 0.000,' city' @ 0.000
72,' Foo' @ 1.000,' Foo' @ 1.000,'Foo' @ 0.000,' Bar' @ 0.000
73,' is' @ 1.000,' is' @ 1.000,"',' @ 0.000",' can' @ 0.000
74,' Bar' @ 0.985,' Bar' @ 0.985,' actually' @ 0.006,' not' @ 0.002
75,'.' @ 0.990,'.' @ 0.990,"',' @ 0.007",'<|im_end|>' @ 0.001
76,'<|im_end|>' @ 0.998,'<|im_end|>' @ 0.998,' This' @ 0.000,' Is' @ 0.000
77,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'\r\n' @ 0.000
78,'<|im_start|>' @ 0.000,'<|endoftext|>' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000
79,'user' @ 0.006,'<|endoftext|>' @ 0.640,'\n' @ 0.332,'<|im_end|>' @ 0.016
80,'\n' @ 1.000,'\n' @ 1.000,'<|im_end|>' @ 0.000,'<|endoftext|>' @ 0.000
81,'Correct' @ 0.982,'Correct' @ 0.982,'Yes' @ 0.004,'I' @ 0.003
82,'!' @ 1.000,'!' @ 1.000,' again' @ 0.000,"',' @ 0.000"
83,'<|im_end|>' @ 0.992,'<|im_end|>' @ 0.992,' Thank' @ 0.003,' You' @ 0.001
84,'\n' @ 1.000,'\n' @ 1.000,'<|im_start|>' @ 0.000,'<|im_end|>' @ 0.000

There's credit attribution once again; it knows the capital of Foo is Bar and it wants to answer immediately ("The" or "Bar"). But after the first unnecessary step, the model once again tries to conform to the trajectory. I also just noticed, the model sometimes tries to end the conversation before fulfulling the user's request. I wonder why that is.

Anyway, I want to try the chunking idea. I feel like a model would kind of struggle to "go back in time" given just chunk (as opposed to a full chat history), so I want to try messing with position IDs.

In [ ]:
from mlx_lm.models.qwen2 import Attention, Qwen2Model, ModelArgs
from mlx_lm.models.base import scaled_dot_product_attention
from typing import Any, Optional
from mlx_lm import generate

class MyRoPE:
    def __init__(self, dims: int, base: float = 10000):
        self.inv_freq = 1 / (base ** (mx.arange(0, dims, 2) / dims))

    def __call__(self, x, position_ids: mx.array, offset: int = 0):
        B, N, L, D = x.shape

        angles = position_ids[:, None, offset:offset + L, None] * self.inv_freq
        cos = mx.cos(angles).astype(x.dtype)
        sin = mx.sin(angles).astype(x.dtype)

        u, v = x[..., :D // 2], x[..., D // 2:]
        return mx.concat([u * cos - v * sin, v * cos + u * sin], axis=-1)

def my_attention_init(self, args: ModelArgs):
    self._base_init(args)
    self.my_rope = MyRoPE(
        dims=args.hidden_size // args.num_attention_heads,
        base=args.rope_theta,
    )

def my_attention_call(
    self,
    x: mx.array,
    mask: Optional[mx.array] = None,
    cache: Optional[Any] = None,
) -> mx.array:
    position_ids = getattr(self, "_position_ids", None)
    if position_ids is None:
        return self._base_call(x, mask, cache)

    B, L, D = x.shape

    queries, keys, values = self.q_proj(x), self.k_proj(x), self.v_proj(x)

    # Prepare the queries, keys and values for the attention computation
    queries = queries.reshape(B, L, self.n_heads, -1).transpose(0, 2, 1, 3)
    keys = keys.reshape(B, L, self.n_kv_heads, -1).transpose(0, 2, 1, 3)
    values = values.reshape(B, L, self.n_kv_heads, -1).transpose(0, 2, 1, 3)

    if cache is not None:
        queries = self.my_rope(queries, position_ids=position_ids, offset=cache.offset)
        keys = self.my_rope(keys, position_ids=position_ids, offset=cache.offset)
        keys, values = cache.update_and_fetch(keys, values)
    else:
        queries = self.my_rope(queries, position_ids=position_ids)
        keys = self.my_rope(keys, position_ids=position_ids)

    output = scaled_dot_product_attention(
        queries, keys, values, cache=cache, scale=self.scale, mask=mask
    )
    output = output.transpose(0, 2, 1, 3).reshape(B, L, -1)
    return self.o_proj(output)

if getattr(Attention, "_base_init", None) is None:
    Attention._base_init = Attention.__init__
Attention.__init__ = my_attention_init

if getattr(Attention, "_base_call", None) is None:
    Attention._base_call = Attention.__call__
Attention.__call__ = my_attention_call

def my_model_call(
    self,
    inputs: mx.array,
    cache=None,
    input_embeddings: Optional[mx.array] = None,
    position_ids: Optional[mx.array] = None,
):
    if position_ids is None:
        position_ids = getattr(self, "_position_ids", None)
    
    for layer in self.layers:
        layer.self_attn._position_ids = position_ids
    
    return Qwen2Model._base_call(self, inputs, cache, input_embeddings)

if getattr(Qwen2Model, "_base_call", None) is None:
    Qwen2Model._base_call = Qwen2Model.__call__
Qwen2Model.__call__ = my_model_call

patched_model, _ = load("mlx-community/Qwen2.5-Coder-7B-Instruct-4bit")

messages = [{"role": "user", "content": "Tell me about the capital of France."}]
prompt = tokenizer.apply_chat_template(messages, add_generation_prompt=True)
print(generate(model, tokenizer, prompt=prompt, max_tokens=50))

patched_model.model._position_ids = mx.arange(100)[None]
print(generate(patched_model, tokenizer, prompt=prompt, max_tokens=50))

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

The capital of France is Paris. It is located in the northern central part of the country and is
The capital of France is Paris. It is located in the northern central part of the country and is